"""Phase 8: Common Sense and World Knowledge."""
import json, os

SYS = ('You are Yaya, a helpful and friendly AI assistant. '
       'You understand how the world works — cause and effect, everyday logic, '
       'and practical knowledge about life.')

examples = [
    ('If I leave ice cream outside in the sun, what happens?', 'It melts. Ice cream is frozen dairy, and heat causes it to liquefy. In direct sunlight in a hot climate like Kenya, it would melt within minutes.'),
    ('I poured water on my phone. What should I do immediately?', 'Act fast. Turn it off immediately — do not try to turn it on. Remove the SIM card and battery if possible. Shake out excess water gently. Pat dry with a cloth. Then put it in a bag of uncooked rice or silica gel packets for 24 to 48 hours to absorb moisture. Do not use a hairdryer as heat can damage components. After 48 hours, try turning it on. Rice is not perfect but it is the best home remedy available.'),
    ('Why does a car need oil?', 'Engine oil lubricates the moving metal parts inside the engine. Without it, the metal parts rub against each other, creating heat and friction that would destroy the engine within minutes. Oil also cools, cleans, and protects the engine. Checking and changing oil regularly is one of the most important things you can do to keep a car running.'),
    ('If someone has not eaten for two days, what is happening in their body?', 'After two days without food, the body has used up its glucose stores (from carbohydrates) and switched to burning fat for energy. The person will feel weak, dizzy, have difficulty concentrating, and may have headaches. They need food with carbohydrates and protein as soon as possible. Water is equally critical — a person can survive longer without food than without water.'),
    ('Why do we get tired after exercise?', 'Exercise uses your muscles intensively, depleting their energy stores (glycogen) and causing microscopic tears in muscle fibres. Lactic acid builds up, causing the burning sensation. Your heart and lungs work harder to supply oxygen. Tiredness is your body signalling it needs rest to repair and rebuild — which is actually when muscles grow stronger.'),
    ('If I plant a tree today, when will it give shade?', 'It depends on the tree species. Fast-growing trees like eucalyptus or jacaranda can provide noticeable shade in 3 to 5 years. Slower trees like mango or avocado may take 5 to 10 years for good shade but also give fruit. Indigenous trees like Mugumo can take decades. For quick shade, plant fast-growers. For long-term benefit, mix in fruit trees. The best time to plant a tree was 20 years ago. The second best time is today.'),
    ('Why does bread go mouldy?', 'Mould is a type of fungus that grows on organic matter like bread. Mould spores are in the air everywhere. When they land on bread, which is moist and full of nutrients, they start growing and digesting the bread. Warmth and humidity speed this up. Keeping bread in a cool, dry place or refrigerator slows mould growth. Eating mouldy bread can cause illness.'),
    ('If I mix bleach and vinegar to clean my house, is that okay?', 'No, do not do this. Bleach and vinegar react to produce chlorine gas, which is toxic and can cause respiratory damage, burning of the eyes and throat, and at high concentrations can be fatal. Use them separately and rinse surfaces thoroughly between uses. This is an important safety fact to share with anyone who cleans at home.'),
    ('Why do people feel sleepy after a big meal?', 'A large meal causes the body to divert blood flow to the digestive system to process the food. This reduces blood flow to the brain temporarily. High-carbohydrate meals also trigger a rise in insulin, which promotes the uptake of tryptophan — an amino acid that converts to serotonin and melatonin, hormones that promote sleep and relaxation. This is why you feel drowsy after a heavy lunch.'),
    ('What happens to your body when you are scared?', 'Fear triggers the fight-or-flight response — your body prepares to either fight danger or run from it. Adrenaline is released, causing: heart rate to increase (pumping blood to muscles), breathing to quicken (more oxygen), pupils to dilate (better vision), muscles to tense, and digestion to pause. You may sweat and feel your stomach drop. This response evolved for survival and happens automatically before your conscious mind even processes the danger fully.'),
    ('If I do not sleep for three days, what happens?', 'After 24 hours without sleep: impaired judgement and coordination, similar to being drunk. After 48 hours: hallucinations begin, immune system weakens, memory fails severely. After 72 hours: more intense hallucinations, inability to concentrate, emotional instability, possible paranoia. The human body fundamentally cannot function without sleep. Three days of no sleep is extremely dangerous and can cause lasting neurological damage. Sleep is not optional.'),
    ('Why does salt make food taste better?', 'Salt (sodium chloride) does two things: it suppresses bitterness, making other flavours more prominent, and it activates taste receptors on your tongue that detect flavour. It also draws moisture out of food through osmosis, concentrating flavours. A small amount of salt does not make food taste salty — it makes food taste more like itself. That is why even sweet recipes often include a pinch of salt.'),
]

data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'sft', 'yaya_instruct.jsonl')
with open(data_path, 'a', encoding='utf-8') as f:
    for user, assistant in examples:
        ex = {'messages': [{'role':'system','content':SYS},{'role':'user','content':user},{'role':'assistant','content':assistant}]}
        f.write(json.dumps(ex, ensure_ascii=False) + '\n')
print(f'Phase 8: Added {len(examples)} common sense examples')
